# Generated by Django 3.2.7 on 2021-10-08 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(default=0)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('rating', models.IntegerField(blank=True)),
                ('sold', models.IntegerField(blank=True)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('V', 'vegetables'), ('F', 'fruits'), ('P', 'poultry'), ('J', 'juice')], max_length=20)),
                ('slug', models.SlugField(default='product-', unique=True)),
                ('ordered', models.BooleanField(default=False)),
                ('measure', models.CharField(blank=True, choices=[('Kg', 'kg'), ('G', 'g'), ('Ltr', 'ltr(s)'), ('None', '')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
