# Generated by Django 3.2.7 on 2021-10-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
