# Generated by Django 3.2.5 on 2021-08-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_listing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
    ]
