# Generated by Django 3.2.5 on 2021-09-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_billingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='user',
        ),
    ]
