# Generated by Django 3.2.7 on 2021-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_billingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='captcha_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='latitude',
            field=models.CharField(max_length=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='longitude',
            field=models.CharField(max_length=100, null=True, verbose_name='Longitude'),
        ),
    ]
