# Generated by Django 3.2.7 on 2021-10-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20211004_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='payment_method',
        ),
    ]
